#!/usr/bin/env python3
"""
View the contents of a ChemSIE JSON extraction file.

This script loads a JSON file that conforms to the ExtractedData schema,
validates it, and prints a human-readable summary of its contents.

Usage:
    python apps/view_extraction_data.py path/to/extraction.json
"""

import sys
import json
import argparse
from pydantic import ValidationError

# As part of the refactor, we assume a project structure where the 'src'
directory is in the PYTHONPATH.
from chemsie.schemas import ExtractedData

def print_section_header(title: str):
    """Prints a formatted section header."""
    print("\n" + "=" * 80)
    print(f" {title.upper()}")
    print("=" * 80)

def main():
    parser = argparse.ArgumentParser(
        description="View and validate a ChemSIE JSON output file.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "json_file",
        help="Path to the JSON file containing data extracted by ChemSIE."
    )
    args = parser.parse_args()

    # --- Load and Validate ---
    print(f"Loading and validating: {args.json_file}")
    try:
        # Pydantic handles both file reading and validation in one step.
        # This replaces the entire 'pickle_loader' system.
        data = ExtractedData.parse_file(args.json_file)
    except FileNotFoundError:
        print(f"Error: File not found at '{args.json_file}'", file=sys.stderr)
        sys.exit(1)
    except ValidationError as e:
        print(f"Error: The JSON file is invalid or does not conform to the schema.", file=sys.stderr)
        print("This is a critical failure, indicating the data is corrupted or was generated by an incompatible version of the pipeline.", file=sys.stderr)
        print("\n--- Pydantic Validation Errors ---", file=sys.stderr)
        print(e, file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: The file at '{args.json_file}' is not a valid JSON file.", file=sys.stderr)
        sys.exit(1)

    print("Validation successful.")

    # --- Display Summary ---
    print_section_header("Extraction Summary")
    print(f"Source Document: {data.source_filename}")
    print(f"Total Molecules Extracted: {len(data.molecules)}")
    print(f"Total Reactions Extracted: {len(data.reactions)}")
    print(f"Total Spectra Datasets Extracted: {len(data.spectra)}")
    if data.errors:
        print(f"Processing Errors Encountered: {len(data.errors)}")


    # --- Display Molecules ---
    if data.molecules:
        print_section_header("Molecules")
        for i, mol in enumerate(data.molecules, 1):
            print(f"  {i}. Molecule ID: {mol.id}")
            print(f"     Label: {mol.label or 'N/A'}")
            print(f"     SMILES: {mol.smiles or 'N/A'}")
            print(f"     InChI: {mol.inchi or 'N/A'}")
            print(f"     Provenance sources: {len(mol.provenance)}")
            # Display the first provenance item for brevity
            if mol.provenance:
                p = mol.provenance[0]
                print(f"       e.g., Page {p.page_number}, Type: {p.source}, Confidence: {p.confidence or 'N/A'}")
            print("-" * 40)

    # --- Display Reactions ---
    if data.reactions:
        print_section_header("Reactions")
        for i, reaction in enumerate(data.reactions, 1):
            print(f"  {i}. Reaction ID: {reaction.id}")
            roles = {'reactant': [], 'reagent': [], 'product': []}
            for comp in reaction.components:
                if comp.role in roles:
                    roles[comp.role].append(comp.molecule_id)
            print(f"     Reactants: {roles['reactant']}")
            print(f"     Reagents: {roles['reagent']}")
            print(f"     Products: {roles['product']}")
            if reaction.yield_value:
                print(f"     Yield: {reaction.yield_value.value} {reaction.yield_value.units}")
            print("-" * 40)

    # --- Display Spectra ---
    if data.spectra:
        print_section_header("Spectra")
        for i, spectrum in enumerate(data.spectra, 1):
            print(f"  {i}. Spectrum ID: {spectrum.id} ({spectrum.nucleus} NMR)")
            print(f"     Associated Molecule ID: {spectrum.molecule_id}")
            print(f"     Solvent: {spectrum.solvent or 'N/A'}")
            print(f"     Peaks Found: {len(spectrum.peaks)}")
            if spectrum.peaks:
                p = spectrum.peaks[0]
                print(f"       e.g., Peak at {p.shift} ppm")
            print("-" * 40)

    # --- Display Errors ---
    if data.errors:
        print_section_header("Processing Errors")
        for error_msg in data.errors:
            print(f"  - {error_msg}")


if __name__ == "__main__":
    # To run this script, ensure the 'src' directory is in your PYTHONPATH:
    # export PYTHONPATH=$PYTHONPATH:./src
    # Or on Windows:
    # set PYTHONPATH=%PYTHONPATH%;./src
    main()
